name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installing dependencies
        run: npm ci

      - name: Compile and build
        run: npm run build -- --base-href=/${{ github.event.repository.name }}/

      - name: Publishing to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/${{ github.event.repository.name }}/browser

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
